-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- Banco de dados: `campustec`

-- --------------------------------------------------------

-- Estrutura da tabela `recrutadores`

CREATE TABLE `recrutadores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomeCompleto` varchar(255) NOT NULL,
  `numeroTel` varchar(20) NOT NULL,
  `setor` varchar(100) NOT NULL,
  `emailPessoal` varchar(255) NOT NULL,
  `emailCorporativo` varchar(255) NULL,
  `senha` varchar(255) NOT NULL,
  `biografia` text NULL,
  `competencias` text NULL,
  `empresa` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `emailPessoal` (`emailPessoal`),
  UNIQUE KEY `emailCorporativo` (`emailCorporativo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci AUTO_INCREMENT=22;

COMMIT;

INSERT INTO `recrutadores` (`nomeCompleto`, `numeroTel`, `setor`, `emailPessoal`, `emailCorporativo`, `senha`, `biografia`, `competencias`, `empresa`)
VALUES
('Steve Jobs', '1234567890', 'Tecnologia', 'stevejobs@apple.com', 'steve@apple.com', 'senha123', 'Steve Jobs foi co-fundador da Apple Inc. e um dos visionários mais notáveis da era da computação pessoal. Ele desempenhou um papel fundamental no design de produtos inovadores como o iPhone, iPad e MacBook, revolucionando a forma como as pessoas interagem com a tecnologia. Jobs era conhecido por sua busca implacável pela perfeição no design e pela criação de um ecossistema que combina hardware e software de forma única.', 'Inovação, liderança, design de produto, visão estratégica', 'Apple'),
('Mark Zuckerberg', '1234567891', 'Tecnologia', 'mark@facebook.com', 'mark@meta.com', 'senha123', 'Mark Zuckerberg é co-fundador e CEO do Facebook (agora Meta), uma das maiores redes sociais do mundo. Desde a criação do Facebook em 2004, ele transformou a maneira como as pessoas se conectam e interagem online. Além de seu trabalho com o Facebook, Zuckerberg também tem investido em novas tecnologias, incluindo realidade virtual e inteligência artificial, com a visão de conectar o mundo em formas ainda mais profundas.', 'Programação, redes sociais, liderança, inovação tecnológica', 'Meta'),
('Elon Musk', '1234567892', 'Tecnologia', 'elon@spacex.com', 'elon@tesla.com', 'senha123', 'Elon Musk é um dos empresários mais influentes do século XXI, conhecido por suas empresas revolucionárias como Tesla e SpaceX. Musk lidera a Tesla na busca por um futuro sustentável com carros elétricos e energia renovável, enquanto a SpaceX visa tornar a exploração espacial acessível e viável para o ser humano. Além disso, Musk tem investido em tecnologias de ponta, como inteligência artificial e transporte de alta velocidade.', 'Inovação, engenharia, empreendedorismo, energia sustentável', 'Tesla, SpaceX'),
('Sundar Pichai', '1234567893', 'Tecnologia', 'sundar@google.com', 'sundar@google.com', 'senha123', 'Sundar Pichai é o CEO do Google e da Alphabet, tendo liderado a transformação do Google em uma das maiores empresas de tecnologia do mundo. Desde que assumiu o cargo de CEO em 2015, ele tem se concentrado no crescimento de áreas como inteligência artificial, computação em nuvem e hardware. Pichai também é conhecido por seu estilo de liderança acessível e por seu trabalho em promover a inclusão dentro da tecnologia.', 'Liderança, inteligência artificial, software, nuvem', 'Google'),
('Jeff Bezos', '1234567894', 'E-commerce', 'jeff@amazon.com', 'jeff@amazon.com', 'senha123', 'Jeff Bezos é o fundador da Amazon, a maior varejista online do mundo. Desde a criação da empresa em 1994, Bezos revolucionou o comércio eletrônico, criando uma plataforma que vende tudo, de livros a produtos tecnológicos. Ele também fundou a Blue Origin, uma empresa espacial focada em viagens comerciais ao espaço. Bezos é um defensor da inovação e da eficiência, sempre buscando novas maneiras de otimizar a experiência do cliente e expandir os negócios.', 'E-commerce, logística, inovação, empreendedorismo', 'Amazon'),
('Bill Gates', '1234567895', 'Tecnologia', 'billgates@microsoft.com', 'billgates@microsoft.com', 'senha123', 'Bill Gates é um dos fundadores da Microsoft e um dos homens mais ricos do mundo. Desde o início da Microsoft nos anos 70, ele tem sido uma figura chave na revolução do software, com o Windows se tornando o sistema operacional dominante no mundo. Após sua saída da Microsoft, Gates se concentrou em filantropia por meio da Fundação Bill e Melinda Gates, focando na saúde global, educação e redução da pobreza.', 'Tecnologia, filantropia, liderança, inovação', 'Microsoft'),
('Larry Page', '1234567896', 'Tecnologia', 'larry@google.com', 'larry@alphabet.com', 'senha123', 'Larry Page é um dos co-fundadores do Google, a gigante de tecnologia que começou como um motor de busca e se expandiu para diversas outras áreas, como publicidade digital, computação em nuvem e inteligência artificial. Além de seu trabalho no Google, Page tem sido um defensor do desenvolvimento de novas tecnologias para melhorar a vida humana e tornar o mundo mais conectado.', 'Programação, inovação, tecnologia, inteligência artificial', 'Google'),
('Sergey Brin', '1234567897', 'Tecnologia', 'sergey@google.com', 'sergey@alphabet.com', 'senha123', 'Sergey Brin é co-fundador do Google e uma das mentes por trás da criação de um dos motores de busca mais poderosos do mundo. Junto com Larry Page, Brin ajudou a fundar o Google, que se tornou a principal ferramenta de pesquisa da internet. Ele também esteve envolvido no desenvolvimento de vários outros projetos no Google, incluindo o sistema operacional Android e o Google Glass.', 'Tecnologia, inovação, empreendedorismo', 'Google'),
('Tim Cook', '1234567898', 'Tecnologia', 'tim@apple.com', 'tim@apple.com', 'senha123', 'Tim Cook é o CEO da Apple, empresa que revolucionou a tecnologia de consumo com dispositivos como o iPhone, iPad e MacBook. Cook assumiu a liderança da Apple após a morte de Steve Jobs e manteve a empresa como uma das mais valiosas do mundo. Ele é conhecido por sua atenção aos detalhes, foco em sustentabilidade e por garantir que a Apple mantenha sua posição como líder em inovação tecnológica.', 'Liderança, inovação, sustentabilidade, estratégia empresarial', 'Apple'),
('Jack Dorsey', '1234567899', 'Tecnologia', 'jack@twitter.com', 'jack@block.com', 'senha123', 'Jack Dorsey é o co-fundador e ex-CEO do Twitter, a plataforma de mídia social que mudou a maneira como as pessoas se comunicam globalmente. Além de seu trabalho no Twitter, Dorsey fundou o Square, uma empresa de pagamentos digitais que facilita transações financeiras para pequenas empresas. Ele é um defensor da simplicidade no design de produtos e serviços tecnológicos.', 'Tecnologia, inovação, fintech, comunicação digital', 'Twitter, Square'),
('Sheryl Sandberg', '1234567800', 'Tecnologia', 'sheryl@facebook.com', 'sheryl@meta.com', 'senha123', 'Sheryl Sandberg foi COO do Facebook e uma das principais responsáveis pelo crescimento e monetização da plataforma. Ela também é autora do best-seller "Lean In", que promove a liderança feminina no ambiente de trabalho. Durante sua carreira, Sandberg defendeu a diversidade e a inclusão no setor de tecnologia, além de liderar iniciativas de marketing e publicidade digital.', 'Gestão, liderança, marketing digital, diversidade', 'Meta'),
('Reed Hastings', '1234567801', 'Tecnologia', 'reed@netflix.com', 'reed@netflix.com', 'senha123', 'Reed Hastings é o co-fundador e CEO da Netflix, a plataforma de streaming que mudou a indústria do entretenimento. Sob sua liderança, a Netflix se transformou de um serviço de aluguel de DVDs para o maior serviço de streaming do mundo, com produções originais e alcance global. Hastings também é um defensor de inovações em mídia e tecnologia.', 'Estratégia empresarial, inovação em mídia, streaming', 'Netflix'),
('Evan Spiegel', '1234567802', 'Tecnologia', 'evan@snapchat.com', 'evan@snap.com', 'senha123', 'Evan Spiegel é o co-fundador e CEO do Snapchat, a plataforma de mensagens efêmeras que inovou a maneira como os jovens se comunicam. Spiegel é conhecido por seu foco em design de produto e inovação, criando uma plataforma que introduziu novas formas de expressão visual, como filtros e lentes em tempo real.', 'Design de produto, inovação social, comunicação digital', 'Snapchat'),
('Marissa Mayer', '1234567803', 'Tecnologia', 'marissa@google.com', 'marissa@verizon.com', 'senha123', 'Marissa Mayer foi uma executiva do Google e CEO do Yahoo, onde ajudou a orientar a empresa em tempos de mudança. Durante sua carreira no Google, Mayer esteve à frente de vários produtos importantes, incluindo o Google Search e o Gmail. Depois de seu tempo no Yahoo, ela continuou a influenciar a indústria de tecnologia, com foco em design de produto e experiência do usuário.', 'Liderança, UX/UI, design de produto, tecnologia', 'Yahoo'),
('Brian Chesky', '1234567804', 'Tecnologia', 'brian@airbnb.com', 'brian@airbnb.com', 'senha123', 'Brian Chesky é o co-fundador e CEO do Airbnb, a plataforma de aluguel de imóveis que transformou a indústria de hospitalidade. Chesky iniciou o Airbnb em 2008, e desde então tem trabalhado para expandir o conceito de "economia compartilhada", permitindo que pessoas alugem suas casas ou apartamentos para hóspedes de todo o mundo.', 'Empreendedorismo, inovação, hospitalidade, economia compartilhada', 'Airbnb');
INSERT INTO `recrutadores` (`nomeCompleto`, `numeroTel`, `setor`, `emailPessoal`, `emailCorporativo`, `senha`, `biografia`, `competencias`, `empresa`)
VALUES
('Maria Aparecida Costa', '1234567810', 'Nutrição', 'mariacosta@nutri.com', 'mariacosta@hospital.com', 'senha123', 'Maria Aparecida Costa é nutricionista com 15 anos de experiência na área hospitalar. Ao longo de sua carreira, ela se especializou em dietas terapêuticas para pacientes com doenças crônicas e promoveu ações educativas para a adoção de hábitos alimentares saudáveis.', 'Nutrição clínica, dietas terapêuticas, educação nutricional, saúde pública', 'Hospital Saúde Viva'),
('João Pereira Silva', '1234567811', 'Nutrição', 'joao@nutri.com', 'joao@clinicadieta.com', 'senha123', 'João Pereira Silva é um nutricionista que atua na área de alimentação coletiva e nutrição esportiva. Com vasta experiência em cardápios nutricionais para grandes empresas e academias, ele foca na otimização do desempenho dos clientes por meio de alimentação adequada.', 'Nutrição esportiva, alimentação coletiva, planejamento alimentar', 'Clínica NutriVita'),
('Carlos Alberto Souza', '1234567812', 'Dietética', 'carlos@dietista.com', 'carlos@nutriempresa.com', 'senha123', 'Carlos Alberto Souza é dietista e tem grande experiência em aconselhamento dietético para perda de peso e controle de doenças metabólicas. Ele tem trabalhado com uma abordagem personalizada de dieta, considerando as necessidades nutricionais e preferências de cada paciente.', 'Dieta personalizada, controle de peso, doenças metabólicas', 'NutriEmpresa'),
('Ana Beatriz Lima', '1234567813', 'Nutrição', 'ana@nutricaoprofissional.com', 'ana@consultoriomelhorar.com', 'senha123', 'Ana Beatriz Lima é especialista em nutrição infantil e atua com o desenvolvimento de estratégias alimentares para crianças e adolescentes com necessidades específicas. Seu trabalho é focado na promoção de uma alimentação saudável desde a infância para prevenir problemas nutricionais na vida adulta.', 'Nutrição pediátrica, saúde infantil, orientação alimentar', 'Consultório Alimentar Infantil'),
('Lucas Martins Ribeiro', '1234567814', 'Nutrição', 'lucas@nutriem.com', 'lucas@emnutri.com', 'senha123', 'Lucas Martins Ribeiro é nutricionista especializado em nutrição para idosos, desenvolvendo planos alimentares adaptados às necessidades nutricionais da terceira idade, visando melhorar a qualidade de vida e prevenir doenças comuns da faixa etária.', 'Nutrição geriátrica, envelhecimento saudável, controle de doenças', 'EmNutri'),
('Renata Martins', '1234567815', 'Nutrição', 'renata@nutriempresa.com', 'renata@empresafood.com', 'senha123', 'Renata Martins é nutricionista especialista em alimentação funcional e atua promovendo a alimentação preventiva e o uso de alimentos que ajudam no fortalecimento do sistema imunológico e na prevenção de doenças.', 'Alimentação funcional, prevenção de doenças, saúde intestinal', 'FoodCorp'),
('Paula Oliveira Souza', '1234567816', 'Nutrição', 'paula@clinicaalimenta.com', 'paula@clinicaalimenta.com', 'senha123', 'Paula Oliveira Souza é nutricionista clínica com foco em nutrição comportamental. Ela trabalha com pacientes que têm dificuldades para mudar hábitos alimentares, ajudando a superar transtornos alimentares e a encontrar uma relação saudável com a comida.', 'Nutrição comportamental, transtornos alimentares, psicologia nutricional', 'Clínica Alimentar'),
('Raquel Oliveira', '1234567817', 'Nutrição', 'raquel@consultorio.com', 'raquel@consultorionutricao.com', 'senha123', 'Raquel Oliveira é nutricionista especializada em nutrição hospitalar, atuando no planejamento de cardápios para unidades de saúde e promovendo a reabilitação nutricional de pacientes em recuperação.', 'Nutrição hospitalar, cardápios terapêuticos, reabilitação nutricional', 'Consultório de Nutrição'),
('Marcos Tadeu Gomes', '1234567818', 'Administração', 'marcos@administra.com', 'marcos@corp.com', 'senha123', 'Marcos Tadeu Gomes é administrador com experiência em gestão estratégica e operacional em empresas de grande porte. Ele tem trabalhado no desenvolvimento de soluções empresariais que visam otimizar recursos e aumentar a competitividade no mercado.', 'Gestão estratégica, administração financeira, planejamento empresarial', 'Corp'),
('Laura Silva Costa', '1234567819', 'Administração', 'laura@admincom.com', 'laura@empresa.com', 'senha123', 'Laura Silva Costa é administradora focada em gestão de pessoas e desenvolvimento organizacional. Ela tem atuado em empresas multinacionais, implementando programas de treinamento e desenvolvimento para melhorar o desempenho das equipes.', 'Gestão de pessoas, treinamento, desenvolvimento organizacional', 'EmpresaCorp'),
('Fernando Almeida', '1234567820', 'Administração', 'fernando@admincorporativo.com', 'fernando@corporativo.com', 'senha123', 'Fernando Almeida é especialista em gestão financeira e controladoria, com experiência em planejamento orçamentário e análise de performance de empresas de diferentes segmentos. Ele tem ajudado empresas a otimizar seus custos e maximizar seus lucros.', 'Gestão financeira, controladoria, planejamento orçamentário', 'Corporativo Ltda'),
('Carla Rodrigues', '1234567821', 'Administração', 'carla@adminbrasil.com', 'carla@brasilcorporate.com', 'senha123', 'Carla Rodrigues é administradora especializada em logística e cadeia de suprimentos. Ela tem atuado na reestruturação de processos logísticos para grandes empresas, promovendo melhorias na distribuição de produtos e na gestão de estoques.', 'Logística, cadeia de suprimentos, gestão de estoques', 'Brasil Corporate'),
('Juliana Martins', '1234567822', 'Enfermagem', 'juliana@enfermeira.com', 'juliana@hospitallink.com', 'senha123', 'Juliana Martins é enfermeira com vasta experiência em cuidados intensivos e emergências. Ela tem sido parte fundamental de equipes de UTI e pronto-socorro, oferecendo cuidados imediatos e especializados a pacientes em estado grave.', 'Cuidados intensivos, emergência, enfermagem clínica', 'Hospital Link'),
('André Luiz Ferreira', '1234567823', 'Enfermagem', 'andre@enfermagemclinic.com', 'andre@clinicavida.com', 'senha123', 'André Luiz Ferreira é enfermeiro especializado em enfermagem geriátrica, oferecendo cuidados de saúde essenciais a idosos, tanto em ambientes hospitalares quanto domiciliares. Ele trabalha para garantir o conforto e bem-estar da terceira idade.', 'Enfermagem geriátrica, cuidados domiciliares, saúde do idoso', 'Clínica Vida'),
('Viviane Souza', '1234567824', 'Enfermagem', 'viviane@enfermeiraclinica.com', 'viviane@saudeintegral.com', 'senha123', 'Viviane Souza é enfermeira que atua na área de oncologia, fornecendo suporte e cuidados a pacientes com câncer, auxiliando na gestão de sintomas e promovendo uma abordagem holística no tratamento.', 'Enfermagem oncológica, cuidados paliativos, suporte ao paciente', 'Saúde Integral'),
('Felipe Costa Rocha', '1234567825', 'Enfermagem', 'felipe@enfermeirohospitalar.com', 'felipe@hospitalluz.com', 'senha123', 'Felipe Costa Rocha é enfermeiro especializado em atendimento de urgência e emergência, com experiência em unidades de pronto-socorro. Ele é responsável por fornecer cuidados rápidos e eficazes a pacientes em situações críticas.', 'Urgência, emergência, cuidados intensivos', 'Hospital Luz'),
('Renata Almeida', '1234567826', 'Segurança do Trabalho', 'renata@segurancadotrabalho.com', 'renata@trabalhaseguro.com', 'senha123', 'Renata Almeida é especialista em segurança do trabalho com 10 anos de experiência na implementação de políticas de segurança em empresas industriais e comerciais. Ela desenvolve treinamentos e programas de prevenção de acidentes no ambiente de trabalho.', 'Prevenção de acidentes, segurança do trabalho, treinamentos', 'TrabalhaSeguro'),
('Carlos Henrique Lima', '1234567827', 'Segurança do Trabalho', 'carlos@segurancatrabalhista.com', 'carlos@empresasegura.com', 'senha123', 'Carlos Henrique Lima é especialista em segurança ocupacional, atuando na identificação e mitigação de riscos no ambiente de trabalho. Ele tem implementado estratégias de segurança para empresas de diferentes setores, garantindo ambientes de trabalho mais seguros e saudáveis.', 'Segurança ocupacional, prevenção de riscos, auditoria', 'Empresa Segura'),
('Paulo Henrique Silva', '1234567828', 'Gastronomia', 'paulo@chefdecozinha.com', 'paulo@cozinhagourmet.com', 'senha123', 'Paulo Henrique Silva é chef de cozinha e consultor gastronômico. Ele tem uma vasta experiência em criação de cardápios para restaurantes de alto padrão e eventos corporativos, com ênfase em pratos contemporâneos e técnicas culinárias inovadoras.', 'Culinária contemporânea, consultoria gastronômica, elaboração de cardápios', 'Cozinha Gourmet'),
('Gabriela Lima', '1234567829', 'Gastronomia', 'gabriela@chefgastronomica.com', 'gabriela@restaurantechef.com', 'senha123', 'Gabriela Lima é chef especializada em gastronomia internacional, com experiência em cozinha francesa e italiana. Ela oferece aulas de culinária e workshops para iniciantes e profissionais que buscam aprimorar suas técnicas culinárias.', 'Gastronomia internacional, culinária francesa, aulas de cozinha', 'Restaurante Chef'),
('Roberto Santos', '1234567830', 'Gastronomia', 'roberto@cozinheiroprofissional.com', 'roberto@restauranterapida.com', 'senha123', 'Roberto Santos é cozinheiro profissional especializado em culinária brasileira, com foco em pratos regionais e tradicionais. Ele também atua como consultor para restaurantes de comida rápida, criando cardápios com foco em qualidade e velocidade.', 'Culinária brasileira, comida rápida, consultoria de restaurantes', 'Restaurante Rápido');

